# application.yml
# Spring 全局配置
spring:
  application:
    name: yui论坛 # 项⽬名
  output:
    ansi:
      enabled: ALWAYS # 控制台输出彩⾊⽇志
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER #Springfox-Swagger兼容性配置


  datasource:
    url: jdbc:mysql://127.0.0.1:3306/forum_db?characterEncoding=utf8&useSSL=false # 数据库连接串 对应5.7.x
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver # 数据库连接驱动 对应5.7.x
# 服务器配置
server:
  port: 58080 # 指定端⼝号
# ⽇志配置
logging:
  pattern:
    dateformat: MM-dd HH:mm:ss
  level:
    root: info # 默认⽇志级别
    com.yui.forum: debug # 指定包的⽇志级别
  file:
    path: D:/log/project/forum # ⽇志保存⽬录


# mybatis 相关配置，单独配置，顶格写
mybatis:
  mapper-locations: classpath:mapper/**/*.xml # 指定 xxxMapper.xml的扫描路径